# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_foodtype_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='storrnums',
            new_name='stornums',
        ),
    ]
