# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180602_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='stornums',
            new_name='storenums',
        ),
    ]
